### ISSUE TITLE
Project 1

### ISSUE THREAD

**Issue by mrugesh1999** [murtazahassan/Learn-OpenCV-in-3-hours#7]
IN OPENCV 3 the cv2.findContours function return 3 values.
namely im2, contours, hierarchy.

The code from project 1 throws an error about the unpacking of value or value assign error.

**Comment by smoonmare** [comment]
@mrugesh1999 have You tried assigning it? what version of opencv do You have?

**Comment by mrugesh1999** [comment]
I was using the older version of open-CV, the new version 4.x.x returns only 2 values.
